#! /bin/sh
# kcminputrc Mouse cursorTheme 'Oxygen_White'
kcminputrc_mouse_cursortheme=oxy-zion
# kcminputrc Mouse cursorSize ''
kcminputrc_mouse_cursorsize=0
# ksplashrc KSplash Theme Default
ksplashrc_ksplash_theme=Minimalistic
# ksplashrc KSplash Engine KSplashX
ksplashrc_ksplash_engine=KSplashQML
# kcmfonts General forceFontDPI 0
kcmfonts_general_forcefontdpi=220
# kdeglobals Locale Language '' # trigger requesting languages from KLocale
kdeglobals_locale_language=en_US
klocale_languages=en_US
