---
AllCops:
  TargetRubyVersion: 2.0

Lint/ParenthesesAsGroupedExpression:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Rails:
  Enabled: true

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/LeadingCommentSpace:
  Enabled: false

Style/SingleLineBlockParams:
  Enabled: false

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInLiteral:
  EnforcedStyleForMultiline: comma
