#!/bin/sh

# On MacBook Pro Retina, on resume from sleep, fix the network
# interfaces going away.

case "$1" in
resume|thaw)
    service network-manager stop
    rm /var/lib/NetworkManager/NetworkManager.state
    service network-manager start
    ;;
esac
